#!/bin/bash

echo -e "\nChoose what you want to know:\n
1. From which ip were the most requests?
2. What is the most requested page?
3. How many requests were there from each ip?
4. What non-existent pages were clients referred to?
5. What time did site get the most requests?
6. What search bots have accessed the site? (UA + IP)"

read -p "Enter your choice [1-6] : " ans
if (( $ans == 1 )); then
	cat apache_logs.txt | awk '{print "IP requests "$2, $1}' | sort -n | uniq -c | sort -nr
fi
